[project]

fullname = "Historische Entscheidungen des Bundesgerichtshofs für Strafsachen"
shortname = "BGH-Strafrecht"
author = "Seán Fobbe and Tilko Swalve"


[version]

semantic = "1.0.0"
dash = "1-0-0"


[license]

data = "Creative Commons Zero 1.0 Universal"
code = "MIT-0"



[doi] # Digital Object Identifier

data.concept = "10.5281/zenodo.4540376"
data.version = "10.5281/zenodo.4540377"

software.concept = "10.5281/zenodo.7847574" 
software.version = "10.5281/zenodo.7847575"

personendaten = "10.5281/zenodo.4568682"
aktenzeichen = "10.5281/zenodo.4569564"


[debug]

toggle = false   # Ob Debugging aktiv ist; Möglichkeiten sind "true" oder "false"
sample = 50   # Die Anzahl der zufällig ausgewählten Entscheidungen, die im Debugging-Modus berücksichtigt werden sollen

cleanrun = false # Ob alle Ergebnisse vor jedem neuen Run gelöscht werden sollen
tesseractskip = true # Tesseract überspringen



[cores]

max = true  # Ob die maximale Anzahl an logischen Kernen genutzt werden soll; Möglichkeiten sind "true" oder "false"
number = 8   # Die Anzahl Rechenkerne, die verwendet werden soll; wird nur berücksichtigt falls "cores.max" auf "false" steht
tessjobs = 4 # Die Anzahl Tesseract Jobs; jeder Tesseract Job ruft bis zu 4 weitere threads



[parallel]

extractPDF = true
lingsummarize = true
multihashes = true



[download]

timeout = 600			# Timeout für Downloads



[quanteda]

tokens_locale = "de_DE" # Locale in denen Tokens analyisert werden



[fig] # Knitr

format = [ "pdf", "png" ] 	# Ausgabe-Format für Diagramme
dpi = 300     	 	# Auflösung für Diagramme
align = "center"    	# Ausrichtung von Diagrammen im Compilation Report

